# Generated by Django 4.2.7 on 2024-11-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_audiencedata_user_alter_emailaccounts_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='messages',
            name='format_type',
            field=models.CharField(choices=[('HTML', 'HTML Message Only'), ('HTML_IMG', 'HTML with Image Attachment'), ('HTML_TO_IMG', 'HTML to Image Conversion'), ('PDF', 'PDF Attachment'), ('IMG_TO_PDF', 'Image to PDF Conversion'), ('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF')], default='HTML', max_length=20),
        ),
    ]
