# Generated by Django 4.2.7 on 2024-11-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_tags_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='format_type',
            field=models.CharField(choices=[('HTML', 'HTML Message Only'), ('HTML_IMG', 'HTML with Image Attachment'), ('HTML_TO_IMG', 'HTML to Image Conversion'), ('PDF', 'PDF Attachment'), ('IMG_TO_PDF', 'Image to PDF Conversion'), ('HTML_TO_PDF', 'HTML to PDF Conversion'), ('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF')], default='HTML', max_length=20),
        ),
    ]
