# Generated by Django 4.2.7 on 2024-11-20 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_messages_format_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'permissions': [('can_use_html', 'Can use HTML Message Only'), ('can_use_html_img', 'Can use HTML with Image Attachment'), ('can_use_html_to_img', 'Can use HTML to Image Conversion'), ('can_use_pdf', 'Can use PDF Attachment'), ('can_use_img_to_pdf', 'Can use Image to PDF Conversion'), ('can_use_html_to_pdf', 'Can use HTML to PDF Conversion'), ('can_use_html_to_img_to_pdf', 'Can use HTML to Image to PDF Conversion')], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
