# Generated by Django 4.2.7 on 2024-11-24 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0013_alter_messages_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwarePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.CharField(blank=True, choices=[('HTML', 'HTML'), ('HTML_IMG', 'HTML_IMG'), ('HTML_TO_IMG', 'HTML_TO_IMG'), ('PDF', 'PDF'), ('IMG_TO_PDF', 'IMG_TO_PDF'), ('HTML_TO_PDF', 'HTML_TO_PDF'), ('HTML_TO_IMG_TO_PDF', 'HTML_TO_IMG_TO_PDF')], help_text='Select the permissions assigned to this user', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='software_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='softwarepermissions',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_permission'),
        ),
    ]
