# Generated by Django 4.2.7 on 2024-11-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_softwarepermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HTML', 'HTML'), ('HTML_IMG', 'HTML_IMG'), ('HTML_TO_IMG', 'HTML_TO_IMG'), ('PDF', 'PDF'), ('IMG_TO_PDF', 'IMG_TO_PDF'), ('HTML_TO_PDF', 'HTML_TO_PDF'), ('HTML_TO_IMG_TO_PDF', 'HTML_TO_IMG_TO_PDF')], max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='softwarepermissions',
            name='permissions',
        ),
        migrations.AddField(
            model_name='softwarepermissions',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='dashboard.permission'),
        ),
    ]
