# Generated by Django 4.2.7 on 2024-11-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_permission_remove_softwarepermissions_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('IMG_TO_PDF', 'Image to PDF'), ('PDF', 'PDF'), ('HTML_TO_PDF', 'HTML to PDF'), ('HTML', 'HTML'), ('HTML_IMG', 'HTML to Image'), ('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF'), ('HTML_TO_IMG', 'HTML to Image')], max_length=255),
        ),
    ]
