# Generated by Django 4.2.7 on 2024-11-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_campaign_sending_from_alter_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='sending_from',
            field=models.CharField(choices=[('inbox', 'inbox'), ('draft', 'draft')], default='inbox', max_length=12),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('HTML_TO_PDF', 'HTML to PDF'), ('IMG_TO_PDF', 'Image to PDF'), ('PDF', 'PDF'), ('HTML_IMG', 'HTML to Image'), ('HTML_TO_IMG', 'HTML to Image'), ('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF'), ('HTML', 'HTML')], max_length=255),
        ),
    ]
