# Generated by Django 4.2.7 on 2024-12-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_campaign_sending_from_alter_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='format_type',
            field=models.CharField(choices=[('HTML', 'HTML Message Only'), ('HTML_IMG', 'HTML with Image Attachment'), ('ONLY_IMG', 'Image as Content'), ('HTML_TO_IMG', 'HTML to Image Conversion'), ('PDF', 'PDF Attachment'), ('IMG_TO_PDF', 'Image to PDF Conversion'), ('HTML_TO_PDF', 'HTML to PDF Conversion'), ('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF')], default='HTML', max_length=20),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('IMG_TO_PDF', 'Image to PDF'), ('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF'), ('HTML_IMG', 'HTML to Image'), ('HTML', 'HTML'), ('HTML_TO_PDF', 'HTML to PDF'), ('ONLY_IMG', 'Image as Content'), ('HTML_TO_IMG', 'HTML to Image'), ('PDF', 'PDF')], max_length=255),
        ),
    ]
