# Generated by Django 4.2.7 on 2024-12-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_messages_content_alter_messages_format_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='site_icons/', verbose_name='Site Icon')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('HTML', 'HTML'), ('HTML_TO_IMG', 'HTML to Image'), ('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF'), ('HTML_IMG', 'HTML to Image'), ('ONLY_IMG', 'Image as Content'), ('IMG_TO_PDF', 'Image to PDF'), ('HTML_TO_PDF', 'HTML to PDF'), ('PDF', 'PDF')], max_length=255),
        ),
    ]
