# Generated by Django 4.2.7 on 2024-12-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_sitesettings_alter_permission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='login_image',
            field=models.ImageField(blank=True, null=True, upload_to='site_icons/', verbose_name='Login Image'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('IMG_TO_PDF', 'Image to PDF'), ('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF'), ('PDF', 'PDF'), ('ONLY_IMG', 'Image as Content'), ('HTML', 'HTML'), ('HTML_TO_IMG', 'HTML to Image'), ('HTML_TO_PDF', 'HTML to PDF'), ('HTML_IMG', 'HTML to Image')], max_length=255),
        ),
    ]
