# Generated by Django 4.2.7 on 2024-12-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_messages_file_name_alter_permission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiencedata',
            name='tag',
            field=models.CharField(default='First Campaign', max_length=50),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('IMG_TO_PDF', 'Image to PDF'), ('HTML_TO_IMG', 'HTML to Image'), ('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF'), ('HTML_IMG', 'HTML to Image'), ('HTML_TO_PDF', 'HTML to PDF'), ('PDF', 'PDF'), ('HTML', 'HTML'), ('ONLY_IMG', 'Image as Content')], max_length=255),
        ),
    ]
