# Generated by Django 4.2.7 on 2024-12-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_audiencedata_tag_alter_permission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='audience_data',
            field=models.CharField(default='Target', max_length=255),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('IMG_TO_PDF', 'Image to PDF'), ('HTML_TO_PDF', 'HTML to PDF'), ('HTML_IMG', 'HTML to Image'), ('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF'), ('PDF', 'PDF'), ('HTML', 'HTML'), ('ONLY_IMG', 'Image as Content'), ('HTML_TO_IMG', 'HTML to Image')], max_length=255),
        ),
    ]
