# Generated by Django 4.2.7 on 2024-12-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_campaign_audience_data_alter_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('created', 'created'), ('processing', 'processing')], default='created', max_length=12),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('HTML', 'HTML'), ('HTML_TO_IMG_TO_PDF', 'HTML to Image to PDF'), ('PDF', 'PDF'), ('IMG_TO_PDF', 'Image to PDF'), ('ONLY_IMG', 'Image as Content'), ('HTML_TO_IMG', 'HTML to Image'), ('HTML_TO_PDF', 'HTML to PDF'), ('HTML_IMG', 'HTML to Image')], max_length=255),
        ),
    ]
